### ISSUE TITLE
[Issue]: Content Collection Block Slow / Unresponsive to Scroll on Android

### ISSUE THREAD

**Issue by ambrozichj** [SparkDevNetwork/Rock.Mobile-Issues#42]
### Describe the Issue in Detail

When using the Content Collection View block on a page to show results, it's difficult to scroll through the results on android. 

I've noticed the results will sometimes only scroll slightly after a few seconds of trying to scroll, and when I tap on a result I will be redirected only a few seconds after the tap. It feels very laggy / unresponsive, this seems like a performance issue. Also, the block will duplicate results ( showing the same 10 results over and over again ) and I'm not sure if this is related to scroll /  performance issues. 

I've tested using different xaml layouts for the results ( stacklayouts, borders, labels,  and contentviews ) all have the same results so it seems like a performance issue with this block as a whole and not just a rendering issue for the results.  

### Can reproduce in

- [X] Orange App
- [X] Blue App

### Steps to Reproduce

Use the "content channel view" block in the mobile app on android. This issue has been tested on the latest version of android 15, 14, and on 12. 

### Expected Behavior

You should be able to scroll through the results and select the result you desire. This works as intended on all IOS versions. 

### Actual Behavior

Slow performance, often the scroll / tap is unresponsive or heavily delayed. 

### Screenshots or Videos

None

### Reproduction XAML

```xml
This happens with any layout format, even when excluding gesture recognizers and just having plain text label elements the issue still persists. 

Below is a basic response layout that I've been testing with.



<Grid RowDefinitions="Auto, Auto, Auto"
      ColumnDefinitions="*, Auto"
      StyleClass="px-16, gap-col-12">
    
    <Grid.Behaviors>
        <Rock:AddCssClassWhenTrueBehavior Value="{Binding IsLastItem}"
                                          ClassName="mb-16" />
    </Grid.Behaviors>
    
    <Label Text="{{ Item.Name | Escape }}"
           StyleClass="body, bold, text-interface-stronger, mt-16"
           MaxLines="2"
           LineBreakMode="TailTruncation"
           Grid.Row="0"
           Grid.Column="0" />
           
    <Label Text="{{ Item.Content | StripHtml | Trim | Escape }}"
           StyleClass="footnote, text-interface-strong"
           MaxLines="2"
           LineBreakMode="TailTruncation"
           Grid.Row="1" 
           Grid.Column="0" />
    
    <Rock:Icon IconClass="chevron-right"
               StyleClass="text-interface-medium"
               Grid.Row="0" 
               Grid.RowSpan="3"
               Grid.Column="1"
               VerticalOptions="Center" />
               
    <BoxView HeightRequest="1"
             StyleClass="mt-16, text-interface-soft"
             IsVisible="{Binding IsLastItem, Converter={Rock:InverseBooleanConverter}}"
             Grid.Row="2" 
             Grid.Column="0" 
             Grid.ColumnSpan="2" />
</Grid>
```

### Mobile Shell Version

v6

### iOS Device Type(s) and iOS Version(s)

None

### Android Device Type(s) and Android Version(s)

Android 14, 8.10

**Comment by sparkdevnetwork-service** [comment]
@ambrozichj Rock is all about community. A key part of strengthening this bond is knowing who we're engaging with. Could I ask you to include your name, organization, and a photo on your GitHub profile? It's a simple way to put faces to names, fostering a more connected and personal community atmosphere.

**Comment by bradencohen** [comment]
Fixed. Will be included in the shell submitted to the Android app store on Thursday.

**Comment by ambrozichj** [comment]
Hey @bradencohen, I just tested it and am still experiencing this issue. Was the fix pushed? 

This was tested on multiple versions of android.

**Comment by bradencohen** [comment]
@ambrozichj can you test on the Android Blue app released today (1.0.85)? The fix should have been rolled in.

**Comment by ambrozichj** [comment]
Yep! I just tested the blue app. It seems like once everything loads it
then scrolls fine like it does on IOS. However, while it is still loading
results ( first 3-10 seconds after searching) the page is super slow and
laggy still. If I try to scroll I get a popup from android saying the app
stopped responding. Once I wait for the page to load then it works fine
again.
