### ISSUE TITLE
[Issue]: Check-in Block Will Not Allow Multiple People to Check-in

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock.Mobile-Issues#61]
### Describe the Issue in Detail

- All of our check-in templates have Check-In Type set to Family. 
- Childrens groups - Check-in Rule: Add On Check In, Age and Grade are used for the groups Pre-k and under use check-in by age, Kender and older are by Grade and Age.
- Volunteer groups - Check-in Rule: Already Belongs
- Special Needs groups: Check-in Rule: Already Belongs, and Special Needs

In testing the new Mobile check-in block I have found that you can't check-in multiple users if the people selected  do not have something to check-in to for the selected schedules.

I have a single kiosk that can check-in Volunteers, Children and Special Needs. Checking in a single person to a schedule and location that they should be able to check-in to works just fine. I have found the issue to happen when a person can't check-in to a specific schedule. 

Example: 2 users, parent and child, checking into volunteering and a childrens class, with the volunteer schedule of "Volunteer Wednesday" and the childrens schedule "Wednesday Childrens". Individually they can check-in just fine, if you select both people and both schedules I receive an error screen after any selections are made(room, ability). Furthermore, when checking in individually, If a person selects a schedule that has nothing available for them then an error screen is shown.

### Can reproduce in

- [ ] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Create and configure a check-in page on your mobile app.
2. When check-in is active try to check a person into a schedule where they have no option to check-in to.
3. See the error message.

### Expected Behavior

If a person can't check-in to a schedule the schedule should be skipped and a firendly message should be shown that says something along the lines of "Little Johnny can't check-in into Volunteer Wednesday", and the rest of the check-in process should work.

### Actual Behavior

When trying to check a person into a schedule that they have no availability for and error message is displayed.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/3d634e39-1935-400a-8fa6-20a22a1c8ad5)
![Image](https://github.com/user-attachments/assets/f57ab75d-c908-4303-8e92-fa7fd7d100f7)
![Image](https://github.com/user-attachments/assets/9d741d3b-937a-43b3-84dd-3386bda6ee91)

### Reproduction XAML

```xml

```

### Mobile Shell Version

v6

### iOS Device Type(s) and iOS Version(s)

iPad 9, iOS 17

### Android Device Type(s) and Android Version(s)

Pixel 9, Android 15

**Comment by bradencohen** [comment]
Would you mind testing this on the latest orange app in the store? We fixed a handful of check-in bugs and this one was likely caught @asdf1nit .

**Comment by asdf1nit** [comment]
@bradencohen I have tested and it is still not working correctly however the behavior is now different. When selecting 2 or more people it will allow you to select the schedules. however after selecting the schedule I get a different error screen that any of the screens above.

![Image](https://github.com/user-attachments/assets/56123f8f-800f-4f4b-9c44-6328f47872fa)
![Image](https://github.com/user-attachments/assets/0824dc5e-9f8f-4f44-80ef-a25999d9e410)

**Comment by asdf1nit** [comment]
Further testing with 2 children on one schedule gave an error message however the labels printed despite receiving an error message and the children were checked.

The behavior does not seem consistent. Another thing I noticed is that sometimes it does check-in the people but gives an error and does not print tags. I can do it back to back and get different results. 

- It always works with one person, it prints a tag and displays success message.
- With 2 children at one time(same schedule, different room/groups) it always ends up in an error message but doing it back to back to back I can have different results. Those different results are
    - On 1st child lets me pick a room then gives an error message but prints tags and checks in
    - Gives an error message after selecting the schedule, no tags no check-in
    - Gives an error after schedule, no tags but did check-in
 - With 3 people(1 volunteer and 2 children) it get's even wilder and is a mix of all the above and additionally sometimes not everyone is checked in.

![Image](https://github.com/user-attachments/assets/abd931bd-983e-471c-aaa1-cabf9dff4f3f)

**Comment by bradencohen** [comment]
Thanks for the due diligence, we're looking into this @asdf1nit .

**Comment by Panha-Sim** [comment]
@asdf1nit Would you mind verifying the Rock version you're using?

I'm currently testing with Rock Core v17.1.

Here's how I have it configured on my server while trying to reproduce the issue. Let me know if there's anything I should change to better match your setup and reproduce the problem.

![Image](https://github.com/user-attachments/assets/0a722d5d-64cb-47c0-9267-833721133ffa)

![Image](https://github.com/user-attachments/assets/9f005157-2cc7-4439-a2ea-dac4fbe64007)

![Image](https://github.com/user-attachments/assets/e43e9618-a6cc-4cb2-a160-dff9d0bd3776)

![Image](https://github.com/user-attachments/assets/bb2fcc59-6421-49d3-b821-9729c71ee8b1)

![Image](https://github.com/user-attachments/assets/0679dad0-3de8-4868-95a6-6eb20481e25b)


Case: "With 2 children at one time(same schedule, different room/groups) it always ends up in an error message but doing it back to back to back I can have different results. Those different results are"

![Image](https://github.com/user-attachments/assets/afa11ced-c37a-4913-a388-a37c6088fa32)

Case: "With 3 people(1 volunteer and 2 children) it get's even wilder and is a mix of all the above and additionally sometimes not everyone is checked in."

![Image](https://github.com/user-attachments/assets/8271079c-1b5e-40d4-97a8-563c25c5841f)

**Comment by asdf1nit** [comment]
@Panha-Sim I'm adding a couple videos that review the setup. There are some differences that I do believe matter here.

I think the main difference is how the template that you're using is set up. In our system I'm using our volunteer template for the check-in block. This template only includes volunteer group types. The additional group types that are included on the check-in block are not a part of that template. In your screenshots above they are, if you remobe the childrens and special needs areas from you template but select those group types in the additional areas on the mobile block settings as shown in the first video the setup will better match what we have.

Here is a recording of the differences on the server. I'm using  V17.1 Alpha for all testing with the Orange App.

https://thearkchurch1-my.sharepoint.com/:v:/g/personal/jonathan_thearkchurch_com/EXmLCv7vXmZLmXAi-QfTA7EBfM6jXn-1QXcn6Kr7cxOvXg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=xnZDPc

Here is a link to a video of a crash on the mobile app

https://thearkchurch1-my.sharepoint.com/:v:/g/personal/jonathan_thearkchurch_com/EUDwl7SRUV5HnTlR-OwO0RcBvmkNYv756H7zylNvESyo1Q?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=8Cw0Bh

Sorry for the late reply I didn't see the email notification.

**Comment by asdf1nit** [comment]
Here is a look at the specific settings for the Volunteer Area Template that the mobile block is using.

https://thearkchurch1-my.sharepoint.com/:v:/g/personal/jonathan_thearkchurch_com/EZqdUMSlXYVGuOtN7zGNGSkBvRSOP51w1kgUzRZIixnn2w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=v6wqw3

**Comment by Panha-Sim** [comment]
@asdf1nit Thanks for the detailed write-up and the video. We’ll take a closer look into the issue. Thanks again 🙂

**Comment by Panha-Sim** [comment]
@asdf1nit, the issue is now fixed in `v1.7.0.11`. It was caused by checking family members into different areas, each with its own schedule. Now, the Shell behaves like the web NextGen Check-In: it shows a Skip button to bypass any unavailable check-in times instead of throwing an error.
