### ISSUE TITLE
[Issue]: Hidden Navigation Bar reapperars after exiting full scren video

### ISSUE THREAD

**Issue by trydyingtolive** [SparkDevNetwork/Rock.Mobile-Issues#75]
### Describe the Issue in Detail

We are building an app that has a custom nav bar. So this particular page we have Hide Navigation Bar checked. When using the play video command after closing the video the Navigation Bar reappears.

### Can reproduce in

- [ ] Orange App
- [x] Blue App

### Steps to Reproduce

Make a page where the nav bar is set to be hidden. Add the following XAML and click the button. Close the video.

```
<Button
    Text="Watch Video"
    Command="{Binding PlayVideo}"
    CommandParameter="https://content.jwplatform.com/manifests/yp34SRmf.m3u8" />
```

### Expected Behavior

The hidden nav bar does not reappear.

### Actual Behavior

The hidden nav bar does reappear. 

### Screenshots or Videos

This is the reappeared nav bar after closing the video

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/10a82be0-0a7a-44b1-a0b2-3c82b46e453a" />

### Reproduction XAML

```xml
<Button
    Text="Watch Video"
    Command="{Binding PlayVideo}"
    CommandParameter="https://content.jwplatform.com/manifests/yp34SRmf.m3u8" />
```

### Mobile Shell Version

1.7.0.8

### iOS Device Type(s) and iOS Version(s)

iPhone 12

### Android Device Type(s) and Android Version(s)

Pixel 8

**Comment by bradencohen** [comment]
This is fixed and the fix has been backported to v7. Can be tested in the next version of the orange app (sometime next week).

**Comment by jessica-gorbett** [comment]
@bradencohen We are still experiencing this issue with Android and iOS in both the orange and blue app. I tested with an Galaxy S22, iPhone 15, and iPad Air. 

![Image](https://github.com/user-attachments/assets/a5646e4a-2abc-4920-9d88-1bd0b0cfcd93)
<img width="1179" height="2556" alt="Image" src="https://github.com/user-attachments/assets/341ce7b8-0d7d-4e17-9a6b-9c0ef35956a1" />
