### ISSUE TITLE
[Issue]: Mobile Check-in Block - Mulitple People

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock.Mobile-Issues#84]
### Describe the Issue in Detail

When checking in multiple people in with the Rock Mobile check-in block an issue is thrown on the mobile app after the person selections are made. The people are checked in and you can confirm this via the attendance records. I use check-in manager to verify.

### Can reproduce in

- [x] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Create a single group that is available for check-in and attach a schedule
2.  Set up mobile check-in block so that it will allow the group you set up to check-in
3. Make sure you have multiple people in your family to check-in with
4. Navigate to the check-in page and select multiple people for check-in
5. See the error

### Expected Behavior

The check-in should happen successfully and show the success screen with multiple people checked in.

### Actual Behavior

There is an error screen shown at the end of the process instead of a success screen.

### Screenshots or Videos

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/7393be02-eaf8-473f-8ceb-ab71c6bbb09b" />

### Reproduction XAML

```xml

```

### Mobile Shell Version

v1.7.0.11

### iOS Device Type(s) and iOS Version(s)

iPhone 13 IOS 15

### Android Device Type(s) and Android Version(s)

Pixel 9 Android 16

**Comment by asdf1nit** [comment]
Just wanted to follow up and see if there is anything I can do to help speed the progress on this along? This is a big one for us as it prevents us fom using mobile check-in for any events where a family needs to check-in vs only 1 individual.

**Comment by Panha-Sim** [comment]
@asdf1nit Thanks for the bug report. The issue is now fixed.

**Comment by jtwilkinsonbema** [comment]
@Panha-Sim what version is this fixed in?

**Comment by asdf1nit** [comment]
@Panha-Sim I tested this on the letest version of the blue app 1.8.0.3 and it is still an issue when trying to check in more than one individual. I can consistently reproduce this issue.

**Additional Details**

The same screenshot included in this issue is still displayed when you select multiple people to check-in. The attendance is recorded in Rock for all individuals who check-in even when the error screen is shown. If you select only one individual for check-in the success screen is shown and everything works as intended.

Here is a video of that happening. https://thearkchurch1-my.sharepoint.com/:v:/g/personal/jonathan_thearkchurch_com/IQA218DFgTD3TanOmfhzhiB8AR9FkbSsO0daZW-YqpasJHQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=IxmFQP

The check-in template that I'm using to test has the following settings

<img width="2177" height="6762" alt="Image" src="https://github.com/user-attachments/assets/0b176aff-de85-4b9d-96df-83a9ecbf5fee" />

**Comment by asdf1nit** [comment]
@Panha-Sim @nairdo can this issue be looked at again?

**Comment by nairdo** [comment]
@asdf1nit Although I'm not involved in managing the developer teams, I'll make sure this one is looked at by the appropriate team.

**Comment by asdf1nit** [comment]
@nairdo  @Panha-Sim I have tested this again in the latest build in the app store, 19.0, which I believe might have been released the same day that I did my testing in the previous comments. This feature is now working for me on my iPhone! Great job guys! Sorry for the false alert a couple days ago, i should have tested it again.

**Comment by asdf1nit** [comment]
@Panha-Sim upon further testing, I have found that this bug is not completely fixed. While it did fix an issue where 2 people could not check-in at the same time, it now throws an error message if more than one person is selected and 2 different schedles are selected and each schedule is for a different group Type.

This bug was not possible to discover befoer this patch as multiple people checking in did not work. Now that it does work, I've started testing for our mobile check-in roll-out and came across this new issue.

If 2 people are selected and the same schedule is selected for each then check-in works as it should.

I was testing this during services today and I took several screenshots of errors (they were the same as the above, no current atendee selected ). It is now getting to the end of service and I no longer have multiple schedules to select from, there's only one schedule available and it's working great.

I know this issues is closed but since this is related I thought I would comment here. I'll follow up this week with additional information.

**Comment by Panha-Sim** [comment]
@asdf1nit Thanks for the additional info, I will reopen the issue since it seems related.

**Comment by Tibincrunch** [comment]
I'm going to close this, as it sounds like the original issue was fixed. If there's a new issue to address, please file a new report with all the needed details to reproduce. Thanks!
